language: java

jdk:
  - oraclejdk8

cache:
    directories:
        - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak
  - cd $HOME/.m2/repository && find -name *.lastUpdated | xargs rm

install: mvn install -Pdistribution -DskipTests=true -B -V

script:
  - mvn test -B
  - mvn -file testsuite/integration-arquillian test -B

sudo: false
